import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  date,
  foreignKey,
  index,
  integer,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

// IDs are UUIDv7 generated by PostgreSQL 18 (tech-stack.md §2.2);
// Better Auth is configured with `generateId: false` to use these defaults.
const id = () =>
  uuid("id")
    .primaryKey()
    .default(sql`uuidv7()`);
const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const updatedAt = () =>
  timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

// ---------------------------------------------------------------------------
// Better Auth core tables (user, session, account, verification, rate_limit)
// ---------------------------------------------------------------------------

export const user = pgTable("user", {
  id: id(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  // Account settings (F-043, F-046, F-052). Region is separate from the language (Flow F.1).
  /** UI and mail language: "de" | "en". */
  locale: text("locale").notNull().default("en"),
  /** When the language was last chosen explicitly – the latest explicit choice wins (Flow F.3). */
  localeChosenAt: timestamp("locale_chosen_at", { withTimezone: true }),
  /** ISO 3166-1 country for date formats, week start and holidays, e.g. "DE", "US". */
  country: text("country").notNull().default("GB"),
  /** ISO 3166-2 subdivision for regional holidays, e.g. "DE-BY"; null = nationwide only. */
  subdivision: text("subdivision"),
  /** "auto" (by country) | "mon" | "sun". */
  weekStart: text("week_start").notNull().default("auto"),
  /** Account switch "Reduce motion" (Q17 a): true = always reduced, false = follow the device. */
  reduceMotion: boolean("reduce_motion").notNull().default(false),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const session = pgTable(
  "session",
  {
    id: id(),
    token: text("token").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: uuid("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [index("session_user_id_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: id(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: uuid("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    password: text("password"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [index("account_user_id_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: id(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const rateLimit = pgTable("rate_limit", {
  id: id(),
  key: text("key").notNull().unique(),
  count: integer("count").notNull(),
  // Milliseconds since epoch → bigint (exceeds int4).
  lastRequest: bigint("last_request", { mode: "number" }).notNull(),
});

/**
 * Per-address auth events for the rate limits per e-mail address (F-041, R-005 follow-up):
 * code requests and failed verifications. `key` is an HMAC of the normalised address – the
 * address itself is never stored here (also not for addresses without an account).
 */
export const authAttempt = pgTable(
  "auth_attempt",
  {
    id: id(),
    key: text("key").notNull(),
    /** "request" (a code mail was asked for) | "failure" (wrong code or password). */
    kind: text("kind").notNull(),
    createdAt: createdAt(),
  },
  (table) => [
    index("auth_attempt_key_kind_created_idx").on(table.key, table.kind, table.createdAt),
  ],
);

// ---------------------------------------------------------------------------
// Trips (F-001 ff., Increment 2)
// ---------------------------------------------------------------------------

/** Planning phase (sitemap §2). "past" is derived from the dates, never stored. */
export const TRIP_PHASES = ["collecting", "voting", "fixed"] as const;
export type TripPhase = (typeof TRIP_PHASES)[number];

/** Member roles (F-004): exactly one organiser ("Orga" in the UI) per trip in the MVP. */
export const MEMBER_ROLES = ["organizer", "member"] as const;
export type MemberRole = (typeof MEMBER_ROLES)[number];

/** Upper limit of members per trip (PRD Q6; open placeholders count too, F-007). */
export const MAX_TRIP_MEMBERS = 30;

export const trip = pgTable(
  "trip",
  {
    id: id(),
    /** Short, non-speaking id in URLs (/trips/<publicId>) – not a secret (sitemap §4). */
    publicId: text("public_id").notNull().unique(),
    name: text("name").notNull(),
    description: text("description"),
    /** Search range, calendar days in the trip's time zone (ISO dates, inclusive). */
    rangeStart: date("range_start", { mode: "string" }).notNull(),
    rangeEnd: date("range_end", { mode: "string" }).notNull(),
    /** "at least … nights" (1–30) and optional "ideally … nights" (≥ min). */
    minNights: integer("min_nights").notNull(),
    preferredNights: integer("preferred_nights"),
    /** Optional deadline for adding dates (F-017). */
    deadline: date("deadline", { mode: "string" }),
    /** Holiday region of the trip (F-016): ISO 3166-1 country + optional ISO 3166-2 subdivision. */
    holidayCountry: text("holiday_country").notNull(),
    holidaySubdivision: text("holiday_subdivision"),
    /** Language of the organiser at creation – for the link preview (sitemap §4). */
    locale: text("locale").notNull().default("en"),
    /** Invite token, 256 bit base64url (F-002: ≥ 128 bit). Renewing replaces it. */
    inviteToken: text("invite_token").notNull().unique(),
    /** "New members can join" (F-004). */
    joinOpen: boolean("join_open").notNull().default(true),
    phase: text("phase", { enum: TRIP_PHASES }).notNull().default("collecting"),
    /** Fixed dates (F-012, Increment 5) – set together with phase "fixed". */
    fixedStart: date("fixed_start", { mode: "string" }),
    fixedEnd: date("fixed_end", { mode: "string" }),
    /** When the dates were fixed – start of the «Vorfreude» ring (design-system §9.12). */
    fixedAt: timestamp("fixed_at", { withTimezone: true }),
    /** Optional voting deadline (F-017, Flow D.1 #3) – never decides automatically. */
    pollDeadline: date("poll_deadline", { mode: "string" }),
    /** When the vote was started (F-010) – phase «voting» since then. */
    pollStartedAt: timestamp("poll_started_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    check("trip_phase_check", sql`${table.phase} in ('collecting', 'voting', 'fixed')`),
    check("trip_range_check", sql`${table.rangeEnd} > ${table.rangeStart}`),
    check("trip_nights_check", sql`${table.minNights} between 1 and 30`),
    check(
      "trip_fixed_check",
      sql`(${table.phase} = 'fixed') = (${table.fixedStart} is not null and ${table.fixedEnd} is not null)`,
    ),
  ],
);

export const tripMember = pgTable(
  "trip_member",
  {
    tripId: uuid("trip_id")
      .notNull()
      .references(() => trip.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** Name in this trip (F-003: unique per trip, may differ from the account name). */
    displayName: text("display_name").notNull(),
    role: text("role", { enum: MEMBER_ROLES }).notNull().default("member"),
    joinedAt: timestamp("joined_at", { withTimezone: true }).notNull().defaultNow(),
    /** Availability submitted (F-007 status "abgegeben", Increment 3). */
    submittedAt: timestamp("submitted_at", { withTimezone: true }),
    /** Voted in the current poll (F-007 status "abgestimmt", Increment 5). */
    votedAt: timestamp("voted_at", { withTimezone: true }),
    /** Last change of the own days or comment (F-007: «abgegeben · zuletzt geändert …»). */
    availabilityUpdatedAt: timestamp("availability_updated_at", { withTimezone: true }),
    /** Optional comment for the group (F-005, ≤ 200 characters, «Juli nur mit Kindern»). */
    comment: text("comment"),
    /**
     * One-off feedback after the first submission (F-005, A3/A7): which calendar import would
     * have helped – "apple" | "google" | "outlook" | "other" | "none" | "skipped".
     */
    importFeedback: text("import_feedback"),
    /**
     * Fixed range («2027-05-05/2027-05-10») for which this member has seen the celebration
     * «Es geht los!» (F-012, Q17 b): once per person and fixing, across devices. A different
     * range fixed later celebrates again; the same range does not.
     */
    celebratedFor: text("celebrated_for"),
  },
  (table) => [
    primaryKey({ columns: [table.tripId, table.userId] }),
    index("trip_member_user_id_idx").on(table.userId),
    // F-003: names unique per trip, case-insensitive – the database guarantees it under
    // parallel renames/joins (R-039); the app checks first and offers a suggestion.
    uniqueIndex("trip_member_trip_name_idx").on(table.tripId, sql`lower(${table.displayName})`),
    uniqueIndex("trip_member_one_organizer_idx")
      .on(table.tripId)
      .where(sql`${table.role} = 'organizer'`),
    check("trip_member_role_check", sql`${table.role} in ('organizer', 'member')`),
    check(
      "trip_member_comment_check",
      sql`${table.comment} is null or char_length(${table.comment}) <= 200`,
    ),
    check(
      "trip_member_import_feedback_check",
      sql`${table.importFeedback} is null or ${table.importFeedback} in ('apple', 'google', 'outlook', 'other', 'none', 'skipped')`,
    ),
  ],
);

/** Stored day states (F-005). "Geht" is the default and never stored (no row = geht). */
export const AVAILABILITY_STATES = ["maybe", "no"] as const;
export type StoredDayState = (typeof AVAILABILITY_STATES)[number];

/**
 * Own availability per day (F-005, Increment 3): only the exceptions «zur Not» / «geht nicht».
 * The composite foreign key on the membership deletes the days when someone leaves or is
 * removed (F-004/F-013) – no orphaned availability.
 */
export const availability = pgTable(
  "availability",
  {
    tripId: uuid("trip_id").notNull(),
    userId: uuid("user_id").notNull(),
    day: date("day", { mode: "string" }).notNull(),
    state: text("state", { enum: AVAILABILITY_STATES }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.tripId, table.userId, table.day] }),
    foreignKey({
      name: "availability_member_fk",
      columns: [table.tripId, table.userId],
      foreignColumns: [tripMember.tripId, tripMember.userId],
    }).onDelete("cascade"),
    check("availability_state_check", sql`${table.state} in ('maybe', 'no')`),
  ],
);

/**
 * Placeholders (F-007): people the organiser expects but who have not joined yet. Each has
 * its own invite link (256 bit like the trip link); whoever joins through it takes the
 * placeholder over (name pre-filled). A claimed placeholder keeps its row so the link can say
 * «already used – you can still join normally» (Flow A.3); it no longer counts or shows.
 * Names are unique per trip together with the members – checked under the trip row lock.
 */
export const tripPlaceholder = pgTable(
  "trip_placeholder",
  {
    id: id(),
    tripId: uuid("trip_id")
      .notNull()
      .references(() => trip.id, { onDelete: "cascade" }),
    displayName: text("display_name").notNull(),
    inviteToken: text("invite_token").notNull().unique(),
    createdAt: createdAt(),
    claimedBy: uuid("claimed_by").references(() => user.id, { onDelete: "set null" }),
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
  },
  (table) => [
    index("trip_placeholder_trip_id_idx").on(table.tripId),
    uniqueIndex("trip_placeholder_trip_name_idx")
      .on(table.tripId, sql`lower(${table.displayName})`)
      .where(sql`${table.claimedAt} is null`),
  ],
);

/**
 * Events for app rate limits outside Better Auth (F-003: joins per trip and IP, failed
 * invite lookups per IP). `key` is an HMAC – IP addresses are never stored here.
 */
export const rateLimitEvent = pgTable(
  "rate_limit_event",
  {
    id: id(),
    key: text("key").notNull(),
    kind: text("kind").notNull(),
    createdAt: createdAt(),
  },
  (table) => [index("rate_limit_event_key_kind_idx").on(table.key, table.kind, table.createdAt)],
);

// ---------------------------------------------------------------------------
// Vote (F-010, F-011, F-012 – Increment 5)
// ---------------------------------------------------------------------------

/** Answers per option (F-011). */
export const VOTE_CHOICES = ["yes", "maybe", "no"] as const;
export type VoteChoice = (typeof VOTE_CHOICES)[number];

/**
 * Options of the trip's vote (F-010): concrete periods (arrival and departure day). One vote
 * per trip in the MVP – it is «open» while the trip is in phase «voting»; options can only be
 * added after the start, never changed (existing votes stay valid). Duplicates are prevented
 * by the unique index.
 */
export const pollOption = pgTable(
  "poll_option",
  {
    id: id(),
    tripId: uuid("trip_id")
      .notNull()
      .references(() => trip.id, { onDelete: "cascade" }),
    startDate: date("start_date", { mode: "string" }).notNull(),
    endDate: date("end_date", { mode: "string" }).notNull(),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex("poll_option_trip_range_idx").on(table.tripId, table.startDate, table.endDate),
    // Target of the composite foreign key of poll_vote (a vote and its option share the trip).
    uniqueIndex("poll_option_id_trip_idx").on(table.id, table.tripId),
    check("poll_option_range_check", sql`${table.endDate} > ${table.startDate}`),
  ],
);

/**
 * One answer per member and option (F-011: «genau eine Stimme») – the primary key makes a
 * double vote impossible, also under parallel requests. Removal/leaving deletes the votes
 * through the membership (F-004); deleting an option or trip cascades too.
 */
export const pollVote = pgTable(
  "poll_vote",
  {
    optionId: uuid("option_id").notNull(),
    tripId: uuid("trip_id").notNull(),
    userId: uuid("user_id").notNull(),
    choice: text("choice", { enum: VOTE_CHOICES }).notNull(),
    updatedAt: updatedAt(),
  },
  (table) => [
    primaryKey({ columns: [table.optionId, table.userId] }),
    index("poll_vote_trip_user_idx").on(table.tripId, table.userId),
    foreignKey({
      name: "poll_vote_option_fk",
      columns: [table.optionId, table.tripId],
      foreignColumns: [pollOption.id, pollOption.tripId],
    }).onDelete("cascade"),
    foreignKey({
      name: "poll_vote_member_fk",
      columns: [table.tripId, table.userId],
      foreignColumns: [tripMember.tripId, tripMember.userId],
    }).onDelete("cascade"),
    check("poll_vote_choice_check", sql`${table.choice} in ('yes', 'maybe', 'no')`),
  ],
);
