/** Symbol ids of public/icons.svg (without the `ww-icon-` prefix). Drift check: scripts/design-assets.test.ts. */
export const ICON_NAMES = [
  "calendar",
  "calendar-plus",
  "share",
  "vote",
  "crown",
  "check",
  "maybe",
  "cross",
  "language",
  "calendar-download",
  "copy",
  "holiday",
  "link",
  "arrow-left",
  "arrow-right",
  "chevron-left",
  "chevron-right",
  "chevron-down",
  "more",
  "close",
  "plus",
  "minus",
  "undo",
  "range",
  "quick-actions",
  "info",
  "warning",
  "success",
  "comment",
  "filter",
  "eye",
  "eye-off",
  "remind",
  "mail",
  "lock",
  "clock",
  "nights",
  "users",
  "user",
  "edit",
  "trash",
  "logout",
  "login",
  "help",
  "sun",
  "star",
  "sparkle",
  "chart",
  "plane",
  "all-available",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
